collections_config:
  pages:
    path: src/content/pages
    name: Pages
    icon: library_books
    url: /[slug]/
  blog:
    path: src/content/blog
    name: Blog
    icon: event_note
    url: /blog/[slug]/
  guides:
    path: src/content/guides
    name: Guides
    icon: import_contacts
    url: /guides/[slug]/
  glossary:
    path: src/content/glossary
    name: Glossary
    icon: spellcheck
    url: /glossary/[slug]/
  industries:
    path: src/content/industries
    name: Industries
    icon: business
    url: /industries/[slug]/
  data:
    path: data
    name: Data
    icon: data_object

data_config:
  site:
    path: data/site.json
  navigation:
    path: data/navigation.json

paths:
  uploads: src/assets/images

editor:
  default_path: /
