import { registerAstroComponent } from "@cloudcannon/editable-regions/astro";
import "@cloudcannon/editable-regions/astro-react-renderer";
import Hero from "../components/heroes/hero/hero.astro";
import LeftRight from "../components/left-right/left-right.astro";
import TextBlock from "../components/text-block/text-block.astro";
import PostHero from "../components/blog/post-hero/post-hero.astro";
import FeatureBlock from "../components/blocks/feature-block.astro";
import ComparisonTable from "../components/blocks/comparison-table.astro";
import CtaBand from "../components/blocks/cta-band.astro";
import FaqAccordion from "../components/blocks/faq-accordion.astro";
import ProofStrip from "../components/blocks/proof-strip.astro";
import Byline from "../components/blocks/byline.astro";
import SourcesList from "../components/blocks/sources-list.astro";
import Breadcrumbs from "../components/blocks/breadcrumbs.astro";

registerAstroComponent("Hero", Hero);
registerAstroComponent("LeftRight", LeftRight);
registerAstroComponent("TextBlock", TextBlock);
registerAstroComponent("PostHero", PostHero);
registerAstroComponent("FeatureBlock", FeatureBlock);
registerAstroComponent("ComparisonTable", ComparisonTable);
registerAstroComponent("CtaBand", CtaBand);
registerAstroComponent("FaqAccordion", FaqAccordion);
registerAstroComponent("ProofStrip", ProofStrip);
registerAstroComponent("Byline", Byline);
registerAstroComponent("SourcesList", SourcesList);
registerAstroComponent("Breadcrumbs", Breadcrumbs);
